id: ko-KR
label: 한국어
translators:
  [
    "eterv",
    "icepeng",
    "Jcurver",
    "firepunch",
    "plrs9816",
    "Heunsig",
    "makepado",
    "gunhoflash",
    "suu3",
    "zwonkim",
  ]
active: true
